version: '3.9'
services:
  db:
    container_name: mysql
    image: mysql:8.0.30
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql@123'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  maildev:
    container_name: mail-dev
    image: maildev/maildev:2.0.5
    ports:
      - '1080:1080'
      - '1025:1025'
    volumes:
      - ./var/data/maildev:/home/maildev/data

volumes:
  db:
    driver: local