-- CATEGORY
CREATE TABLE category
(
    category VARCHAR(255) NOT NULL,
    name     VARCHAR(255),
    PRIMARY KEY (category)
);

-- USERS
CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email      VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    password   VARCHAR(255),
    provider   VARCHAR(255),
    role       VARCHAR(255),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    verified   BOOLEAN   NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (email)
);

-- TOKEN
CREATE TABLE token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expire_at  TIMESTAMP(6),
    token      VARCHAR(255),
    user_id    BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- POST
CREATE TABLE post
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    content           TEXT,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description       TEXT,
    thumbnail         VARCHAR(255),
    title             VARCHAR(255),
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    views             BIGINT    NOT NULL,
    category_category VARCHAR(255),
    user_id           BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (category_category) REFERENCES category (category),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

-- NEWSLETTER
CREATE TABLE newsletter
(
    email              VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    news_letter_status VARCHAR(255),
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (email)
);

-- CONTACT
CREATE TABLE contact
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    email          VARCHAR(255),
    first_name     VARCHAR(255),
    last_name      VARCHAR(255),
    message        TEXT,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_entity_id BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_entity_id) REFERENCES users (id)
);

-- COMMENT
CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    comment    TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name       VARCHAR(255),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    post_id    BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (post_id) REFERENCES post (id)
);

-- PERSISTENT_LOGINS
CREATE TABLE persistent_logins
(
    username  VARCHAR(64) NOT NULL,
    series    VARCHAR(64) PRIMARY KEY,
    token     VARCHAR(64) NOT NULL,
    last_used TIMESTAMP   NOT NULL
);

-- SPRING_SESSION
CREATE TABLE spring_session
(
    primary_id            CHAR(36) NOT NULL,
    session_id            CHAR(36) NOT NULL,
    creation_time         BIGINT   NOT NULL,
    last_access_time      BIGINT   NOT NULL,
    max_inactive_interval INT      NOT NULL,
    expiry_time           BIGINT   NOT NULL,
    principal_name        VARCHAR(100),
    CONSTRAINT spring_session_pk PRIMARY KEY (primary_id)
);

CREATE UNIQUE INDEX spring_session_ix1 ON spring_session (session_id);
CREATE INDEX spring_session_ix2 ON spring_session (expiry_time);
CREATE INDEX spring_session_ix3 ON spring_session (principal_name);

-- SPRING_SESSION_ATTRIBUTES
CREATE TABLE spring_session_attributes
(
    session_primary_id CHAR(36)     NOT NULL,
    attribute_name     VARCHAR(200) NOT NULL,
    attribute_bytes    BYTEA        NOT NULL,
    CONSTRAINT spring_session_attributes_pk PRIMARY KEY (session_primary_id, attribute_name),
    CONSTRAINT spring_session_attributes_fk
        FOREIGN KEY (session_primary_id)
            REFERENCES spring_session (primary_id)
            ON DELETE CASCADE
);
