spring:
  profiles:
    active: mysql
email:
  token:
    validity: 3600
#http:
#  port: 8080

server:
  error:
    include-message: always
    path: /authenticate/404
  port: 8080
  servlet:
    session:
      timeout: 15m
      tracking-modes: cookie

site:
  base:
    url: http://localhost:8080

