spring:
  groovy:
    template:
      cache: false
  #      MySQL Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/KRDB?createDatabaseIfNotExist=true
    username: root
    password: mysql@123
  session:
    store-type: jdbc
    timeout: 100000
    jdbc:
      initialize-schema: always
      table-name: SPRING_SESSION
  flyway:
    baseline-on-migrate: true
    enabled: true

  # Thymeleaf Cache disabled
  thymeleaf:
    cache: false

  #Mail configuration
  mail:
    host: localhost
    username: hello
    password: hello
    port: 1025
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          ssl:
            trust: '"*"'
          starttls:
            enable: false
          timeout: 3000
          writetimeout: 5000

  # Image upload configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB
