spring:
  profiles:
    active: mysql
  # Image upload configuration
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 20MB

server:
  error:
    include-message: always
    path: /authenticate/404
  port: 8080
  servlet:
    session:
      timeout: 15m
      tracking-modes: cookie

email:
  token:
    validity: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info

site:
  base:
    url: http://localhost:8080